
local veh=443


setModelHandling(veh, "mass", 5500.0)
setModelHandling(veh, "turnMass", 33187.9)
setModelHandling(veh, "dragCoeff", 2.0)
setModelHandling(veh, "centerOfMass", { 0.0, 0.0, -0.2 } )
setModelHandling(veh, "percentSubmerged", 90)
setModelHandling(veh, "tractionMultiplier", 0.65)
setModelHandling(veh, "tractionLoss", 0.8)
setModelHandling(veh, "tractionBias", 0.40)
setModelHandling(veh, "numberOfGears", 5)
setModelHandling(veh, "maxVelocity", 110.0)
setModelHandling(veh, "engineAcceleration", 20.0)
setModelHandling(veh, "engineInertia", 20.0)
setModelHandling(veh, "driveType", "rwd")
setModelHandling(veh, "engineType", "diesel")
setModelHandling(veh, "brakeDeceleration", 3.5)
setModelHandling(veh, "brakeBias", 0.40)
setModelHandling(veh, "ABS", false)
setModelHandling(veh, "steeringLock", 30.0)
setModelHandling(veh, "suspensionForceLevel", 1.4)
setModelHandling(veh, "suspensionDamping", 0.06)
setModelHandling(veh, "suspensionHighSpeedDamping", 0.0)
setModelHandling(veh, "suspensionUpperLimit", 0.45)
setModelHandling(veh, "suspensionLowerLimit", -0.25)
setModelHandling(veh, "suspensionFrontRearBias", 0.55)
setModelHandling(veh, "suspensionAntiDiveMultiplier", 0.0)
setModelHandling(veh, "seatOffsetDistance", 0.45)
setModelHandling(veh, "collisionDamageMultiplier", 0.20)
setModelHandling(veh, "monetary", 5000)
setModelHandling(veh, "modelFlags", 0x6008)
setModelHandling(veh, "handlingFlags", 0x200)
setModelHandling(veh, "headLight", 0)
setModelHandling(veh, "tailLight", 1)
setModelHandling(veh, "animGroup", 2)
