veh=504
setModelHandling(veh, "mass", 1000.0)
setModelHandling(veh, "turnMass", 2500.3)
setModelHandling(veh, "dragCoeff", 4.0)
setModelHandling(veh, "centerOfMass", { 0.0, 0.0, -0.3 } )
setModelHandling(veh, "percentSubmerged", 80)
setModelHandling(veh, "tractionMultiplier", 0.70)
setModelHandling(veh, "tractionLoss", 0.88)
setModelHandling(veh, "tractionBias", 0.55)
setModelHandling(veh, "numberOfGears", 4)
setModelHandling(veh, "maxVelocity", 200.0)
setModelHandling(veh, "engineAcceleration", 35.0)
setModelHandling(veh, "engineInertia", 5.0)
setModelHandling(veh, "driveType", "awd")
setModelHandling(veh, "engineType", "petrol")
setModelHandling(veh, "brakeDeceleration", 6.1)
setModelHandling(veh, "brakeBias", 0.55)
setModelHandling(veh, "ABS", false)
setModelHandling(veh, "steeringLock", 35.0)
setModelHandling(veh, "suspensionForceLevel", 1.0)
setModelHandling(veh, "suspensionDamping", 0.10)
setModelHandling(veh, "suspensionHighSpeedDamping", 5.0)
setModelHandling(veh, "suspensionUpperLimit", 0.25)
setModelHandling(veh, "suspensionLowerLimit", -0.20)
setModelHandling(veh, "suspensionFrontRearBias", 0.35)
setModelHandling(veh, "suspensionAntiDiveMultiplier", 0.0)
setModelHandling(veh, "seatOffsetDistance", 0.60)
setModelHandling(veh, "collisionDamageMultiplier", 0.40)
setModelHandling(veh, "monetary", 15000)
setModelHandling(veh, "modelFlags", 0x40000100)
setModelHandling(veh, "handlingFlags", 0x00303303)
setModelHandling(veh, "headLight", 1)
setModelHandling(veh, "tailLight", 2)
setModelHandling(veh, "animGroup", 1)


--[Handling Converted by Pothole Studios]--
